#!/bin/bash -e

echo '### STOPPING SQUID'
if which initctl && initctl --version | grep -i upstart
    then
    echo "upstart installed, try use upstart..."
    echo "stopping squid..."
    sudo initctl stop squid || echo "squid seems to be down" 2>&1 >> $LOGFILE
    sleep 5
    while ps aux | grep squid | grep -v grep
    do
        echo "squid is still up, waiting 3 seconds..."
        sleep 3
    done
    echo 'squid is down!'
else
    echo "no upstart installed, try use init script..."
    if which invoke-rc.d >/dev/null 2>&1; then
        # have to use invoke-rc.d, like told here:
        # http://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3.2
        sudo invoke-rc.d squid stop
    else
        sudo /etc/init.d/squid stop
    fi
fi

echo '### STOPPING DNSMASQ'
if which invoke-rc.d >/dev/null 2>&1; then
    # have to use invoke-rc.d, like told here:
    # http://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3.2
    sudo invoke-rc.d dnsmasq stop
else
    sudo /etc/init.d/dnsmasq stop
fi

exit 0

